name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Change this if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSHPASS GitHub Action
        uses: matheusvanzan/sshpass-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: administrator
          # Password will not be used for login, but if sudo is needed, it may still ask
          password: ${{ secrets.SSH_PASSWORD }}
          run: |
            cd /var/www/myapp
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            sudo systemctl restart php8.1-fpm
            sudo systemctl restart nginx


