name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH & sshpass
        run: |
          sudo apt update
          sudo apt install -y openssh-client sshpass

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Ensure the correct port and server IP
          ssh-keyscan -p 2222 159.65.28.61 >> ~/.ssh/known_hosts

      - name: Deploy to Server (SSH + Password)
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@159.65.28.61 -p 2222 << 'EOF'
          cd /var/www/myapp
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan key:generate
          exit
          EOF

      - name: Restart Nginx
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@159.65.28.61 -p 2222 "sudo systemctl restart nginx"
